import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import Header from "@/components/global/Header";
import Footer from "@/components/global/Footer";
import { dir } from "i18next";
import { languages } from "@/app/i18n/settings";
import Providers from "./providers";

const poppins = Poppins({
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lang) => ({ lang }));
}

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  return (
    <html lang={lang} dir={dir(lang)} suppressHydrationWarning>
      <body
        className={`${poppins.className} bg-slate-50 dark:bg-slate-900 text-slate-950 dark:text-slate-100`}
      >
        <Providers lang={lang}>
          <Header lang={lang} />
          {children}
          <Footer lang={lang} />
        </Providers>
      </body>
    </html>
  );
}
